import type { Metadata } from "next";
import "./globals.css";
import Sidebar from "@/components/Sidebar";
import SidebarHamMenu from "@/components/SidebarHamMenu";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="flex flex-col min-h-screen">
        <div className="flex">
          <div>
            <SidebarHamMenu />
          </div>
          <aside className="hidden md:flex flex-col gap-2 w-64 bg-white border-r p-4 min-h-screen">
            <Sidebar />
          </aside>
          <div className="flex-1">{children}</div>
        </div>
      </body>
    </html>
  );
}
